### PR TITLE
Lcg/powershell out warning

### PR DESCRIPTION
**Pull request by lamont-granquist**

### CODE REVIEW

**Comment by lamont-granquist** [comment]
Use this link to remove the whitespace deltas:

https://github.com/opscode-cookbooks/windows/pull/235/files?w=0

**Comment by lamont-granquist** [comment]
@jdmundrawala @ksubrama @smurawski ping

**Comment by smurawski** [comment]
:+1:

**Comment by jdmundrawala** [comment]
:+1:

**Comment by jdmundrawala** [comment]
thanks @lamont-granquist

**Pull request merged**
