### PR TITLE
use Chef.set_resource_priority_array to suppress warning

### PR DESCRIPTION
**Pull request by lamont-granquist**

### CODE REVIEW

**Comment by jdmundrawala** [comment]
do we need to set the provider priority as well?

**Comment by lamont-granquist** [comment]
@someara @jdmundrawala @smurawski could use some eyes on this.

see chef/chef#3349 for why undefining the existing class is bad.

**Comment by lamont-granquist** [comment]
Does it wire itself up explicitly?

**Comment by jdmundrawala** [comment]
Looks like it:
https://github.com/opscode-cookbooks/windows/blob/master/libraries/windows_package.rb#L215

**Comment by lamont-granquist** [comment]
The cookbook version hardcodes itself to the cookbook version of the provider, yeah

**Comment by jdmundrawala** [comment]
:+1:

**Comment by lamont-granquist** [comment]
If people want to do both they're gonna have to setup a provides alias anyway to wire up a way to hit the internal core windows_package resource, so I think there's nothing we need to do to the provider mapping there either.

**Comment by smurawski** [comment]
:+1:

**Comment by jdmundrawala** [comment]
I don't think people have ever done that

**Comment by lamont-granquist** [comment]
The guy in chef/chef#3349 wants to use both of them...

**Pull request merged**
