### PR TITLE
Fix resource priority

### PR DESCRIPTION
**Pull request by jdmundrawala**
I think the old logic would never match?

cc @lamont-granquist

### CODE REVIEW

**Comment by lamont-granquist** [comment]
No the `Chef.set_resource_priority_array` is `chef >= 12.3.0` so I'm trying to catch `12.0.0 <= chef_version < 12.3.0` with the else block.

**Comment by lamont-granquist** [comment]
(we don't have dynamic *resource* resolution with the priority array stuff before 12.3.0, and don't have the chef_class stuff before then either)

**Comment by jdmundrawala** [comment]
Right, but it looks like `Chef.respond_to?(:set_resource_priority_array)` check only happens
if `Gem::Version.new(Chef::VERSION) < Gem::Version.new('12')`.

```ruby
if Gem::Version.new(Chef::VERSION) < Gem::Version.new('12')
  if Chef.respond_to?(:set_resource_priority_array)
   ....
```
Since `Gem::Version.new('12.3.0') < Gem::Version.new('12') == false`, `if Chef.respond_to?(:set_resource_priority_array)` will never run.

**Comment by lamont-granquist** [comment]
lol, yes, i can't read.

:+1:

**Pull request merged**
