### PR TITLE
Add check for cert existence before binding

### LINKED ISSUE #230: windows_certificate_binding fails ungracefully if cert doesn't exist
Currently, when windows_certificate_binding resource fails due to a non-existent cert, it puts out a confusing windows error about sessions. The resource should check for the certs existence and, if it doesn't exist, fail with something more descriptive.

### PR DESCRIPTION
**Pull request by tophercullen**
Add check for cert existence before binding

If a cert doesn't exist, it shouldn't try and bind it.
Display a better error message than netsh would give
Fixes #230

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by ksubrama** [comment]
Hey, the CLA checker is complaining because your commit isn't being linked to the correct github account.  It's pointing to a jamberry email address.  Could you sign the CLA and amend your commit.  The PR looks good otherwise and I'd be happy to merge it in.

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by tophercullen** [comment]
Welp, I'm just going to resubmit a pull request. I thought I was just rewriting my own commit history D-;

**Pull request closed without merging**
